# Autogenerated by nbdev

d = { 'settings': {'branch': '1', 'doc_baseurl': '/1', 'doc_host': 'https://1.github.io', 'git_url': 'https://github.com/1/1', 'lib_path': '1'},
  'syms': {'1.core': {'1.core.foo': ('core.html#foo', '1/core.py')}}}
